server:
  port: 8080
  servlet:
    context-path: /api/inditex-test
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

spring:
  application:
    name: inditex-test

  messages:
    basename: messages
